import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

// Step 10b item 5 — instruction tables for the lending transaction decoders (D11).
// Writes packages/risk/src/lending/ix-names.ts: for every instruction of klend, kvault and the three Jupiter Lend
// programs, its 8-byte discriminator, its name and the names of its accounts in order (nested account groups are
// flattened in IDL order; a leaf name already used gets its group as prefix). Sources are the IDLs shipped in the
// SDKs: klend 1.25.0 and kvault 2.2.2 in klend-sdk 12.0.1 (Anchor 0.29 format, discriminator =
// sha256("global:<snake_name>")[0..8]); Jupiter Lend vaults, liquidity and lending in @jup-ag/lend-read 0.0.14
// (Anchor 0.30 format, discriminator in the IDL); the flashloan program in @jup-ag/lend 0.3.0. The package never imports an SDK: this file is the bridge.
// Usage: tsx scripts/risk/lending-ix-table.ts
const require = createRequire(import.meta.url);
const OUT = 'packages/risk/src/lending/ix-names.ts';

type Acc = { name: string; accounts?: Acc[] };
type Ix = { name: string; accounts: Acc[]; discriminator?: number[] };
type Idl = {
  instructions: Ix[];
  version?: string;
  metadata?: { version: string };
  types?: Array<{ name: string; type: { variants?: Array<{ name: string }> } }>;
};

const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const globalDisc = (name: string) =>
  createHash('sha256')
    .update(`global:${snake(name)}`)
    .digest()
    .subarray(0, 8)
    .toString('hex');

function flatten(accs: Acc[], group = '', seen = new Set<string>()): string[] {
  const out: string[] = [];
  for (const a of accs) {
    if (a.accounts) {
      out.push(...flatten(a.accounts, a.name, seen));
      continue;
    }
    const n = seen.has(a.name) && group ? `${group}.${a.name}` : a.name;
    seen.add(a.name);
    out.push(n);
  }
  return out;
}

const klendDir = join(dirname(require.resolve('@kamino-finance/klend-sdk')), 'idl');
const klend = JSON.parse(readFileSync(join(klendDir, 'klend.json'), 'utf8')) as Idl;
const kvault = JSON.parse(readFileSync(join(klendDir, 'kvault.json'), 'utf8')) as Idl;

// Jupiter Lend IDLs are bundled into lend-read's module as `var <name>_default = {...}` literals.
const lendRead = readFileSync(require.resolve('@jup-ag/lend-read'), 'utf8');
function bundledIdl(name: string): Idl {
  const i = lendRead.indexOf(`var ${name}_default = {`);
  if (i < 0) throw new Error(`IDL ${name} not found in lend-read`);
  const start = lendRead.indexOf('{', i);
  const end = lendRead.indexOf('\n};', i);
  // the literal is plain JSON-compatible JS (unquoted keys); evaluate it as an expression
  return new Function(`return (${lendRead.slice(start, end + 2)});`)() as Idl;
}

// The flashloan program's IDL is bundled into @jup-ag/lend 0.3.0 as `const instructions$N = [...]` after its address.
function lendBundledInstructions(address: string): Idl {
  const dir = join(realpathSync('node_modules/@jup-ag/lend'), 'dist', 'shared');
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.mjs'))) {
    const src = readFileSync(join(dir, f), 'utf8');
    const m = new RegExp(`const address(\\$\\d+) = "${address}"`).exec(src);
    if (!m) continue;
    const i = src.indexOf(`const instructions${m[1]} = [`, m.index);
    const start = src.indexOf('[', i);
    const end = src.indexOf('\n];', i);
    const metaAt = src.indexOf(`const metadata${m[1]} = `, m.index);
    const meta = new Function(
      `return (${src.slice(src.indexOf('{', metaAt), src.indexOf('\n};', metaAt) + 2)});`,
    )() as { version: string };
    return {
      instructions: new Function(`return (${src.slice(start, end + 2)});`)() as Ix[],
      metadata: meta,
    };
  }
  throw new Error(`IDL for ${address} not found in @jup-ag/lend`);
}

const programs: Array<[string, string, Idl, 'global' | 'idl']> = [
  ['KLEND', 'KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD', klend, 'global'],
  ['KVAULT', 'KvauGMspG5k6rtzrqqn7WNn3oZdyKqLKwK2XWQ8FLjd', kvault, 'global'],
  ['JL_VAULTS', 'jupr81YtYssSyPt8jbnGuiWon5f6x9TcDEFxYe3Bdzi', bundledIdl('vaults'), 'idl'],
  ['JL_LIQUIDITY', 'jupeiUmn818Jg1ekPURTpr4mFo29p46vygyykFJ3wZC', bundledIdl('liquidity'), 'idl'],
  ['JL_LENDING', 'jup3YeL8QhtSx1e253b2FDvsMNC87fDrgQZivbrndc9', bundledIdl('lending'), 'idl'],
  [
    'JL_FLASHLOAN',
    'jupgfSgfuAXv4B6R2Uxu85Z1qdzgju79s6MfZekN6XS',
    lendBundledInstructions('jupgfSgfuAXv4B6R2Uxu85Z1qdzgju79s6MfZekN6XS'),
    'idl',
  ],
];

const lines: string[] = [
  '// Generated by scripts/risk/lending-ix-table.ts from the IDLs in klend-sdk 12.0.1 (klend 1.25.0, kvault 2.2.2)',
  '// and @jup-ag/lend-read 0.0.14 (vaults 0.1.5, liquidity 0.1.4, lending 0.1.4), flashloan from @jup-ag/lend 0.3.0.',
  '// Do not edit by hand.',
  '// discriminator hex → [instruction name, account names in order]',
  'export type IxTable = Readonly<Record<string, readonly [string, readonly string[]]>>;',
  '',
];
for (const [k, address, idl, mode] of programs) {
  const version = idl.version ?? idl.metadata?.version;
  lines.push(`/** ${address} (IDL ${version}) */`);
  lines.push(`export const ${k}_IX: IxTable = {`);
  for (const ix of idl.instructions) {
    const disc =
      mode === 'global'
        ? globalDisc(ix.name)
        : Buffer.from(ix.discriminator as number[]).toString('hex');
    lines.push(`  '${disc}': ['${ix.name}', ${JSON.stringify(flatten(ix.accounts))}],`);
  }
  lines.push('};', '');
}
// enum variant names used to label configuration changes (index = Borsh tag)
const variants = (idl: Idl, name: string) => {
  const t = idl.types?.find((x) => x.name === name);
  if (!t?.type.variants) throw new Error(`enum ${name} not in IDL`);
  return t.type.variants.map((v) => v.name);
};
for (const [k, idl, name] of [
  ['KLEND_CONFIG_MODES', klend, 'UpdateConfigMode'],
  ['KLEND_MARKET_MODES', klend, 'UpdateLendingMarketMode'],
  ['KVAULT_CONFIG_FIELDS', kvault, 'VaultConfigField'],
] as const) {
  lines.push(`/** ${name} variants, by tag. */`);
  lines.push(`export const ${k}: readonly string[] = ${JSON.stringify(variants(idl, name))};`, '');
}
writeFileSync(OUT, lines.join('\n'));
console.log(
  `wrote ${OUT}: ${programs.map(([k, , idl]) => `${k} ${idl.instructions.length}`).join(', ')}`,
);
