import type { Asset } from '@colosseum/schemas';

/**
 * Source of truth for the asset registry (seeded into the `assets` table by `pnpm db:seed`).
 * Static facts only: mints (verified 2026-09-30, docs/structurer/VERIFICATION.md V6), token programs, gates,
 * redemption paths. No yield numbers: those live in `yield_observations` with source and timestamp.
 *
 * The BRL leg is abstract: zero yield, no FX risk against a BRL goal, cap and mint path are parameters.
 * BRS-specific data (issuer mint path, Nora limits) is added only after docs/GATES.md marks G-Nora PASSED.
 */
export const BRL_LEG_CAP_WEIGHT_DEFAULT = 0.3;

const gatesXstock = [
  'front-ends geo-block US/UK/CA/AU; token moves freely',
  'primary redemption 24/5 with KYC and a minimum (xStocks FAQ)',
  'Token-2022 permanentDelegate: issuer can move tokens',
  'Token-2022 pausable and transferHook extensions',
];

export const REGISTRY: Asset[] = [
  {
    id: 'usdc',
    symbol: 'USDC',
    name: 'USD Coin (cash buffer)',
    kind: 'cash',
    chain: 'solana',
    mint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    tokenProgram: 'token',
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: 1,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Circle',
      creditExposure: 'Circle reserves',
      oracle: 'n/a (unit)',
      redemptionPath: 'hold; Circle primary for institutions',
      redemptionTime: 'instant on DEX',
      gates: [],
    },
    provenance: 'live',
  },
  {
    id: 'usdt',
    symbol: 'USDT',
    name: 'Tether USD (funding only)',
    kind: 'cash',
    chain: 'solana',
    mint: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    tokenProgram: 'token',
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: 0,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Tether',
      creditExposure: 'Tether reserves',
      oracle: 'n/a (unit)',
      redemptionPath: 'swap to USDC via Jupiter',
      redemptionTime: 'instant on DEX',
      gates: [],
      label: 'funding asset, converted to USDC before allocation',
    },
    provenance: 'live',
  },
  {
    id: 'kamino-usdc',
    symbol: 'kUSDC',
    name: 'Kamino Lend USDC (main market)',
    kind: 'usd_yield',
    chain: 'solana',
    mint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    tokenProgram: 'token',
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: 0.6,
    mintPath: 'lending_deposit',
    metadata: {
      issuer: 'Kamino Finance (protocol)',
      creditExposure: 'over-collateralised borrowers of the main market; smart-contract risk',
      oracle: 'Scope / Pyth (Kamino reserve config)',
      redemptionPath: 'withdraw from reserve D6q6wuQSrifJKZYpR1M8R4YawnLDtDsMmWM1NbBmgJ59',
      redemptionTime: 'instant while reserve has liquidity; utilisation-gated',
      gates: [],
      docsUrl: 'https://kamino.com/docs',
    },
    provenance: 'live',
  },
  {
    id: 'syrupusdc',
    symbol: 'syrupUSDC',
    name: 'Maple syrupUSDC',
    kind: 'usd_yield',
    chain: 'solana',
    mint: 'AvZZF1YaZDziPY2RCK4oJrRVrbN3mTD9NL24hPeaZeUj',
    tokenProgram: 'token',
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: 0.4,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Maple Finance',
      creditExposure: 'institutional over-collateralised loans (Syrup pool)',
      creditLeg: true,
      oracle: 'pool exchange rate (Ethereum) / Jupiter price',
      redemptionPath: 'Jupiter DEX on Solana; primary redemption on Ethereum without KYC',
      redemptionTime: 'instant on DEX; primary queue on Ethereum',
      gates: ['bridged asset: Solana liquidity depends on DEX depth'],
      docsUrl: 'https://maple.finance',
    },
    provenance: 'live',
  },
  {
    id: 'usdy',
    symbol: 'USDY',
    name: 'Ondo US Dollar Yield',
    kind: 'usd_yield',
    chain: 'solana',
    mint: 'A1KLoBrKBde8Ty9qtNQUtq3C2ortoC3u7twggz7sEto6',
    tokenProgram: 'token',
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: 0.4,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Ondo Finance',
      creditExposure: 'short-dated US Treasuries and bank deposits (tokenized note)',
      oracle: 'USDY price oracle (accrues by price)',
      redemptionPath: 'Jupiter DEX (secondary); primary mint/redeem needs KYC, non-US, minimum',
      redemptionTime: 'instant on DEX; primary T+ days',
      gates: [
        'primary redemption: KYC, non-US persons, minimum size',
        'Brazil listed as restricted jurisdiction for primary access (Ondo eligibility)',
      ],
      docsUrl: 'https://docs.ondo.finance',
    },
    provenance: 'live',
  },
  {
    id: 'spyx',
    symbol: 'SPYx',
    name: 'SP500 xStock',
    kind: 'equity',
    chain: 'solana',
    mint: 'XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W',
    tokenProgram: 'token-2022',
    decimals: 8,
    eligibleProfiles: ['high_risk'],
    capWeight: 0.3,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Backed Finance (xStocks)',
      creditExposure: 'issuer SPV holding the underlying ETF',
      oracle: 'Chainlink 24/5 equities streams / Jupiter price',
      redemptionPath: 'Jupiter DEX 24/7; primary redemption 24/5 via issuer',
      redemptionTime: 'instant on DEX (thin weekends); primary T+ days',
      gates: gatesXstock,
      docsUrl: 'https://docs.xstocks.fi',
    },
    provenance: 'live',
  },
  {
    id: 'qqqx',
    symbol: 'QQQx',
    name: 'Nasdaq xStock',
    kind: 'equity',
    chain: 'solana',
    mint: 'Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ',
    tokenProgram: 'token-2022',
    decimals: 8,
    eligibleProfiles: ['high_risk'],
    capWeight: 0.3,
    mintPath: 'dex_swap',
    metadata: {
      issuer: 'Backed Finance (xStocks)',
      creditExposure: 'issuer SPV holding the underlying ETF',
      oracle: 'Chainlink 24/5 equities streams / Jupiter price',
      redemptionPath: 'Jupiter DEX 24/7; primary redemption 24/5 via issuer',
      redemptionTime: 'instant on DEX (thin weekends); primary T+ days',
      gates: gatesXstock,
      docsUrl: 'https://docs.xstocks.fi',
    },
    provenance: 'live',
  },
  {
    id: 'brl-leg',
    symbol: 'BRL',
    name: 'BRL leg (abstract; on-chain reais)',
    kind: 'brl_stable',
    chain: 'solana',
    mint: undefined,
    tokenProgram: undefined,
    decimals: 6,
    eligibleProfiles: ['income', 'accumulation', 'high_risk'],
    capWeight: BRL_LEG_CAP_WEIGHT_DEFAULT,
    mintPath: 'unavailable',
    metadata: {
      issuer: undefined,
      creditExposure: 'issuer of the BRL stablecoin (to be set at gate G-Nora)',
      oracle: 'n/a (1:1 BRL)',
      redemptionPath: 'issuer redeem to USDC (to be set at gate G-Nora)',
      redemptionTime: 'to be set at gate G-Nora',
      gates: ['primary mint limited to approved minters'],
      label: 'BRS mint via Nora: integration in progress',
    },
    provenance: 'live',
  },
];

export const REGISTRY_BY_ID = new Map(REGISTRY.map((a) => [a.id, a]));
export const getAsset = (id: string): Asset => {
  const a = REGISTRY_BY_ID.get(id);
  if (!a) throw new Error(`unknown asset ${id}`);
  return a;
};
