// The probe inputs of the reviews of #216 and #227, verbatim: 24 natural answers and the attack
// classes. `[KEY]` stands for a reference; each test maps the keys to the figures its path has.
export const FIGURE_PROBES: Array<[string, string[]]> = [
  [
    '1 meaning-changers',
    [
      'You get at least [Y] from the reserve.',
      'You are sure to get [Y] from it.',
      'The reserve gives you [Y] each and every time.',
      'You make [NV] each on Nvidia.',
      'Nvidia is worth [NP] per token, and only [NV] in all.',
      'Nvidia costs more than [NP] now.',
      'Nvidia is worth up to [NV] today.',
      'Nvidia is worth less than [NV] today.',
      'Nvidia is nearly [NS] of the vault.',
      'You could lose up to [NV] on Nvidia.',
      'You stand to make [NV] on Nvidia.',
      'Nvidia made you [NV] so far.',
      'Nvidia is [NV] in the red.',
      'Nvidia is [NV] above what you put in.',
      'Nvidia is [NV] cheaper than before.',
      'Nvidia is [NS] overvalued.',
      'Nvidia has a [NS] chance of beating the market.',
      'Your money is [NS] safe in Nvidia.',
      'Nvidia beats the market by [NS] in a typical twelvemonth.',
      'You owe [NV] in tax on Nvidia.',
      'The fee on Nvidia is [NS] of what you hold.',
    ],
  ],
  [
    '2 splits',
    [
      'What does Nvidia return in a year? About [NS].',
      'Expected yearly return on Nvidia. [NS].',
      'Nvidia will keep rising. Think [NS].',
      'Nvidia return, year after year: about [NS].',
      'Nvidia, year after year, makes about [NS].',
      'Yearly return on Nvidia:\n[NS]',
      'Yearly return on Nvidia:\n- [NS]',
      'Nvidia returns a lot… [NS] to be exact.',
      'Nvidia returns, e.g. [NS].',
      'Nvidia annual return (approx. [NS]) is strong.',
      'Nvidia grows every year by about\n\n[NS]\n\nand that is a lot.',
    ],
  ],
  [
    '3 sentinel / invisible',
    [
      'Nvidia is worth [NV]\u0001B.',
      'Nvidia re͏turns about [NS] a ye͏ar.',
      'Nvidia holds [NA] mil͏lion units.',
      'Nvidia holds [NA] mil️lion units.',
      'Nvidia rеturns about [NS] a yеar.',
      'Nvidia holds [NA] miᅠllion units.',
      'Nvidia holds [NA] ㅤ [NA] units.',
      'Nvidia is worth ［NV］.',
      'Nvidia is worth ｛｛fact:vault:value｝｝.',
      'Nvidia holds [NA] mіllion units.',
    ],
  ],
  [
    '4 languages',
    [
      'Nvidia rinde [NS] al año.',
      'Nvidia vale [NV] millones.',
      'Nvidia rapporte [NS] par an.',
      'Nvidia holds [NA] Mio units.',
      'Nvidia holds [NA] lakh units.',
      'Nvidia holds [NA] crore units.',
      'Nvidia is worth [NV] MM.',
      'Nvidia holds [NA] tsd units.',
    ],
  ],
  [
    '5 yield promises',
    [
      'Its quoted yield is [Y] a year, measured from past rates.',
      'You can count on [Y] a year from the reserve.',
      'The reserve locks in [Y] a year.',
      'The reserve pays [Y] every year.',
      'The reserve pays [Y] a year, like clockwork.',
      'A steady [Y] a year comes from the reserve.',
      'The reserve reliably pays [Y] a year.',
      'You get [Y] a year from the reserve, no matter what.',
      'The reserve pays a fixed [Y] a year.',
      'Your money earns [Y] a year in the reserve, with no risk of loss.',
      'The reserve pays [Y] a year for as long as you hold it.',
      'Put it in the reserve and collect [Y] a year.',
      'The reserve can not pay less than [Y] a year.',
      'Next year the reserve pays [Y] again.',
      'The reserve earns [Y] a year on top of [NV] you hold in Nvidia.',
    ],
  ],
  [
    '6 wrong asset',
    [
      'Tesla trades at [NP].',
      'TSLAx trades at [NP].',
      'Tesla is volatile. It trades at [NP].',
      'Your gold is worth [NV].',
      'Your biggest stock is Tesla, worth [NV].',
      'Elon’s company is worth [NV] to you.',
      'The electric car maker is worth [NV].',
      'Your cash is worth [NV].',
      'USDC: [NV].',
      'Nvidia and Tesla are worth [NV] and [TV].',
      'Tesla is worth [NV], more than Nvidia.',
      'The reserve is worth [NV].',
    ],
  ],
  [
    '8 natural answers',
    [
      'Your Nvidia holding is worth [NV] right now. That is [NA] units at a reference price of [NP] each.',
      'Your Nvidia is worth about [NV] at the current reference price.',
      'You hold [NA] NVDAx, worth [NV] at today’s reference price. That’s about [NS] of your vault.',
      'Selling all of your Nvidia today would cost about [NX] in the worst measured conditions.',
      'Selling everything at once would cost roughly [NX] for Nvidia and [TX] for Tesla, based on the worst regime Bearing has measured. Your dollar-yield reserve and cash have no measured exit cost.',
      'About [CS] of your vault is cash, which is [CV] in USDC.',
      'Cash makes up [CS] of your vault ([CV]). The rest is split between Nvidia, Tesla and the reserve.',
      'Weekend exit capacity for Nvidia is [NW], so I can’t tell you how it compares to weekdays yet.',
      'There are no weekend samples for NVDAx yet, so that figure is unknown rather than zero.',
      'I can’t rank them for you, but here are the measured figures: selling Nvidia would cost about [NX], and selling Tesla about [TX]. Both are worst-case measurements.',
      'Nvidia’s measured exit cost is [NX] and Tesla’s is [TX], so you can compare them directly.',
      'Your vault is worth [W] in total. Nvidia is [NV], Tesla is [TV], the reserve is [RV] and cash is [CV].',
      'Your vault is worth [W]. Nvidia is the largest stock position at [NS], against a target of [NT].',
      'Nvidia is currently [NS] of your vault, and its target is [NT], so it is close to where you set it.',
      'The reserve’s quoted yield is [Y] a year. That is a past observation, not a promise.',
      'Nvidia’s largest measured drawdown was [ND], and its annualised volatility is [NVOL]. It can move a lot.',
      'Nvidia has dropped as much as [ND] in the past, which gives you a sense of the downside.',
      'At the current price of [NP], your [NA] units of Nvidia come to [NV].',
      'Right now Nvidia trades at [NP]. You hold [NA] units, for a total value of [NV].',
      'Your Nvidia position: **[NV]** ([NS] of the vault).',
      'Your dollar-yield reserve is worth [RV].',
      'If you sold it all today, the cost would be about [NX] of the amount sold. That is the worst case measured; it would likely be lower during market hours.',
      'Your Nvidia holding is up to date as of the last read: [NV]. I don’t have a figure for how much it has gained since you bought it.',
      'Tesla would cost about [TX] to sell and Nvidia about [NX]. I can’t say which is cheaper, but both figures are measured at the reference size.',
    ],
  ],
  [
    'G1 legit shapes',
    [
      'The reserve’s quoted yield is [Y] a year.',
      'Its current rate is now about [Y] a year at the last reading.',
      'The reserve currently yields [Y] a year.',
      'The reserve yields [Y] a year.',
      'The reserve’s yield is [Y] a year right now.',
      'Right now the reserve yields about [Y] a year, though that can change.',
      'The reserve’s yield is [Y] a year, based on the latest quote.',
      'It’s worth [RV], and its quoted yield is currently [Y] a year.',
      'Its quoted yield is [Y] a year, and after the haircut [YH].',
      'Its quoted yield is [Y] a year. After the haircut, its quoted yield is [YH] a year.',
      'The reserve’s quoted yield is [Y] a year. That is a past observation, not a promise.',
      'O rendimento cotado é [Y] ao ano. Isso é uma observação passada, não uma promessa.',
      'O rendimento cotado é [Y] ao ano.',
      'A reserva rende atualmente [Y] ao ano.',
      'A reserva atualmente rende [Y] ao ano.',
      'A reserva rende [Y] ao ano, segundo a última cotação.',
      'O rendimento atual da reserva é de cerca de [Y] ao ano.',
      'jlUSDC currently yields [Y] a year.',
      'Your dollar-yield reserve currently yields [Y] a year.',
      'The reserve’s quoted yield is [Y] a year, though it can change.',
      'The reserve’s quoted yield is [Y] a year (a past reading).',
    ],
  ],
  [
    'G2 optional parts / trailing owner',
    [
      'Its current yield is [Y] a year for you.',
      'The current rate for you is [Y] a year.',
      'Its quoted yield is [Y] a year for decades.',
      'Its quoted yield is [Y] a year for ever.',
      'Its quoted yield is [Y] a year for years.',
      'Its current yield is [Y] a year from tomorrow.',
      'Its current yield is [Y] a year from January.',
      'Its current yield is [Y] a year on autopilot.',
      'Its current yield is [Y] a year of profit.',
      'Its current yield is [Y] a year of pure-profit.',
      'Its current yield is [Y] a year for free.',
      'Its current yield is [Y] a year for retirement.',
      'Its current yield is [Y] a year on everything.',
      'Its current yield is [Y] a year for eternity.',
      'Your current yield is [Y] a year.',
      'Your current rate is now about [Y] a year.',
      'The current yield on your money is [Y] a year.',
      'The current yield of waiting is [Y] a year.',
      'Your guaranteed-rate’s current yield is [Y] a year.',
      'The bank-beating reserve’s current yield is [Y] a year.',
      'The reserve’s current risk-free-rate is [Y] a year.',
      'The current rate of return is [Y] a year.',
      'The current yield from doing-nothing is [Y] a year.',
      'Its past yield of [Y] a year.',
      'Its current rate at [Y] a year.',
      'The latest yield for holders is now [Y] a year right now at the last reading for everyone.',
      'Its current yield is [Y] a month.',
      'Its current yield is [Y] a day.',
      'Its current yield is [Y] annually so far.',
    ],
  ],
  [
    'G3 subject-verb clause',
    [
      'The reserve now pays you [Y] a year.',
      'The reserve now pays [Y] a year.',
      'You currently get [Y] a year.',
      'You now pays [Y] a year.',
      'Everyone now pays [Y] a year.',
      'Saving now pays [Y] a year.',
      'Patience now pays [Y] a year.',
      'Holding currently pays [Y] a year.',
      'Everything currently yields [Y] a year.',
      'Nvidia currently yields [Y] a year.',
      'Tesla now pays [Y] a year.',
      'Cash now pays [Y] a year.',
      'Gold now pays [Y] a year.',
      'Money now pays [Y] a year.',
      'It pays [Y] a year now.',
      'It has paid [Y] a year so far.',
      'So far it has paid [Y] and it keeps paying.',
      'Now it pays [Y] a year.',
      'Today, guaranteed pays [Y] a year.',
      'Now, retirement pays [Y] a year.',
      'Risklessly pays [Y] a year now.',
      'Now, effortlessly yields [Y] a year.',
      'Today everything pays [Y] a year today.',
      'Bearing now pays [Y] a year.',
      'Tenonfi now pays [Y] a year.',
      'This now pays [Y] a month.',
    ],
  ],
  [
    'G4 remainder carries the promise',
    [
      'You can retire on it, and its quoted yield is currently [Y] a year.',
      'There is no way to lose, and its current yield is [Y] a year.',
      'It never goes down, and its quoted yield is currently [Y] a year.',
      'This is free money: its current rate is [Y] a year.',
      'Sit back and relax: the reserve now pays [Y] a year.',
      'You earn while you sleep, and its current yield is [Y] a year.',
      'Your money is insured, and its current yield is [Y] a year.',
      'It is as good as cash, and its current yield is [Y] a year.',
      'Your capital is preserved, and its current yield is [Y] a year.',
      'You get paid like a salary, and the reserve currently pays [Y] a year.',
      'Put everything in the reserve: its current yield is [Y] a year.',
      'You will love this: its current yield is [Y] a year.',
      'Expect this to continue, and its current yield is [Y] a year.',
      'It is the smart choice, and its current yield is [Y] a year.',
      'It is a sure thing, and its current yield is [Y] a year.',
      'Better than a bank, and its current yield is [Y] a year.',
      'Year after year without exception: its current yield is [Y] a year.',
      'In ten years you are rich: its current yield is [Y] a year.',
      'Every year, like a paycheck, and the reserve currently pays [Y] a year.',
      'Yours to enjoy in perpetuity: its current yield is [Y] a year.',
      'Indefinitely, and I mean it, its current yield is [Y] a year.',
      'Nvidia is worth [NV], and its quoted yield is currently [Y] a year.',
      'Nvidia earns too, and its quoted yield is currently [Y] a year.',
      'The reserve is the steadier part of your vault, and its quoted yield is currently [Y] a year.',
      'It never goes down. Its quoted yield is [Y] a year.',
      'Its quoted yield is [Y] a year. You may rely on it.',
      'Its quoted yield is [Y] a year. And that is yours in perpetuity.',
      'Its quoted yield is [Y] a year. Nothing changes that.',
      'Its quoted yield is [Y] a year. Enjoy it, year after year.',
    ],
  ],
  [
    'G5 Portuguese',
    [
      'Fique tranquilo: o rendimento atual é [Y] ao ano.',
      'Sem sustos, e a reserva hoje paga [Y] ao ano.',
      'Você recebe isso sem falta: o rendimento cotado é [Y] ao ano.',
      'O rendimento atual é [Y] ao ano, sem falta.',
      'O rendimento atual é [Y] ao ano hoje e amanhã.',
      'O seu rendimento atual é [Y] ao ano.',
      'A taxa atual é de [Y] ao mês.',
      'Dinheiro fácil: a reserva hoje rende [Y] ao ano.',
      'Você não perde nada, e a reserva hoje rende [Y] ao ano.',
      'Pode se aposentar com isso: o rendimento atual é [Y] ao ano.',
      'O rendimento atual do seu-dinheiro é [Y] ao ano.',
      'Hoje, tudo rende [Y] ao ano.',
      'Agora poupar paga [Y] ao ano.',
      'O rendimento cotado é [Y] ao ano. E isso continua.',
      'O rendimento atual é [Y] ao ano, e isso é seu.',
      'Nvidia hoje rende [Y] ao ano.',
    ],
  ],
  [
    'G6 self-describing ignores the sentence before',
    [
      'Yearly return you can count on: It is [NS] of the vault.',
      'Yearly return you can count on. It is [NS] of the vault.',
      'What will you earn in a year? In all, [W].',
      'Expected yearly income: A total of [W].',
      'Expected yearly income.\nTotal: [W].',
      'What does Nvidia return in a year? A share of about [NS].',
      'Your cut of the gains each year. A portion of [NS].',
      'How much will Nvidia gain this year? Its target is [NT].',
      'What will you make on Nvidia this year? It is worth [NV].',
      'What is the yearly profit? The amount is [NA].',
      'Guaranteed yearly payout. Altogether [W].',
      'Next year’s gain on Nvidia. Target: [NT].',
      'How much does Nvidia pay a year? The cost is [NX].',
      'What does Nvidia lose in a bad year? Its price is [NP].',
      'Nvidia doubles every year. Its value: [NV].',
      'Nvidia will fall by half. It is worth [NV].',
      'What will Nvidia return in a year?\n\nWorth [NV].',
      'Your yearly dividend from Nvidia: units, [NA].',
      'Yearly return on Nvidia. Nvidia: [NS].',
      'Yearly return on Nvidia. Nvidia is [NS] of the vault.',
      'What does it pay a year? Total: [W].',
      'Quanto rende ao ano? No total, [W].',
      'What will you earn in a year? The vault is worth [W].',
    ],
  ],
];
