import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Writes the typed copies of the committed ABIs (idl/evm/*.json) the adapter reads with:
//
//   pnpm --filter @colosseum/chain-evm abi
//
// packages/chain-evm/test/units.test.ts fails while packages/chain-evm/src/vault/generated/abi.ts is
// not what idl/evm holds, so a change to a contract's interface comes with a run of this in the same
// pull request. It lives here and not in the package: a chain package reads no file.

const repo = join(import.meta.dirname, '..', '..');
const idl = join(repo, 'idl', 'evm');
const out = join(repo, 'packages', 'chain-evm', 'src', 'vault', 'generated', 'abi.ts');

const ABI_FILES = {
  BASKET_VAULT_ABI: 'BasketVault',
  VAULT_FACTORY_ABI: 'VaultFactory',
  INDEX_REGISTRY_ABI: 'IndexRegistry',
  VAULT_BEACON_ABI: 'VaultBeacon',
} as const;

const header = `// Generated by scripts/evm/abi-types.ts from idl/evm. Do not edit.
// VaultConfig.json is not copied: VaultFactory carries every function and error of it.
`;
const body = Object.entries(ABI_FILES)
  .map(([name, file]) => {
    const abi = readFileSync(join(idl, `${file}.json`), 'utf8');
    return `\n/** idl/evm/${file}.json */\nexport const ${name} = ${abi.trim()} as const;\n`;
  })
  .join('');
writeFileSync(out, header + body);
console.log(`${out}: ${Object.keys(ABI_FILES).length} ABIs`);
