import { readFileSync, writeFileSync } from 'node:fs';

// PLAN-ANALYTICS item 11 — the fact sheets' methodology, generated from §5 of docs/risk/PLAN-ANALYTICS.md into
// apps/api/src/facts-methodology.ts (`pnpm risk:facts-methodology`). tests/risk-layer/facts-methodology.test.ts fails
// when the two differ, so the API never serves a method the plan no longer states.
export const methodologySection = (doc: string) => {
  const start = doc.indexOf('## 5. Methods');
  const end = doc.indexOf('\n## ', start + 1);
  if (start < 0 || end < 0) throw new Error('§5 not found in PLAN-ANALYTICS.md');
  return doc.slice(start, end).trim();
};
if (process.argv[1]?.endsWith('gen-methodology.ts')) {
  const text = methodologySection(readFileSync('docs/risk/PLAN-ANALYTICS.md', 'utf8'));
  writeFileSync(
    'apps/api/src/facts-methodology.ts',
    `// Generated by scripts/risk/facts/gen-methodology.ts from docs/risk/PLAN-ANALYTICS.md §5. Do not edit.\nexport const FACTS_METHODOLOGY = ${JSON.stringify(text)};\n`,
  );
  console.log(`apps/api/src/facts-methodology.ts: ${text.length} characters`);
}
