CREATE TABLE "risk_lending_events" (
	"signature" text NOT NULL,
	"event_key" text NOT NULL,
	"slot" double precision NOT NULL,
	"block_time" timestamp with time zone NOT NULL,
	"chain" text NOT NULL,
	"venue" text NOT NULL,
	"program" text NOT NULL,
	"market" text,
	"pool" text,
	"kind" text NOT NULL,
	"ix" text,
	"caller" text,
	"flows" jsonb NOT NULL,
	"detail" jsonb NOT NULL,
	"method_version" text NOT NULL,
	"source" text NOT NULL,
	"method" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL,
	"provenance" "provenance" NOT NULL,
	CONSTRAINT "risk_lending_events_signature_event_key_pk" PRIMARY KEY("signature","event_key")
);
--> statement-breakpoint
CREATE TABLE "risk_lending_positions" (
	"market" text NOT NULL,
	"collateral_asset" text NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	"chain" text NOT NULL,
	"venue" text NOT NULL,
	"positions" integer NOT NULL,
	"positions_with_debt" integer,
	"positions_state_unknown" integer DEFAULT 0 NOT NULL,
	"collateral_units" double precision NOT NULL,
	"collateral_usd" double precision,
	"debt_usd" double precision,
	"debt_by_asset" jsonb,
	"ltv_buckets_pct" jsonb NOT NULL,
	"buckets" jsonb NOT NULL,
	"ltv_null" integer NOT NULL,
	"ltv_null_units" double precision NOT NULL,
	"top1" double precision,
	"top3" double precision,
	"top10" double precision,
	"usd_null_reason" text,
	"method_version" text NOT NULL,
	"source" text NOT NULL,
	"method" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL,
	"provenance" "provenance" NOT NULL,
	CONSTRAINT "risk_lending_positions_pk" PRIMARY KEY("market","collateral_asset","observed_at","method")
);
--> statement-breakpoint
CREATE TABLE "risk_lending_snapshots" (
	"account" text NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	"kind" text NOT NULL,
	"chain" text NOT NULL,
	"venue" text NOT NULL,
	"market" text NOT NULL,
	"symbol" text,
	"role" text,
	"slot" double precision,
	"supplied" double precision,
	"borrowed" double precision,
	"available" double precision,
	"share_lent_out" double precision,
	"supply_apr" double precision,
	"borrow_apr" double precision,
	"supply_apy" double precision,
	"borrow_apy" double precision,
	"price_usd" double precision,
	"supplied_usd" double precision,
	"borrowed_usd" double precision,
	"usd_null_reason" text,
	"detail" jsonb NOT NULL,
	"method_version" text NOT NULL,
	"source" text NOT NULL,
	"method" text NOT NULL,
	"fetched_at" timestamp with time zone NOT NULL,
	"provenance" "provenance" NOT NULL,
	CONSTRAINT "risk_lending_snapshots_account_observed_at_kind_pk" PRIMARY KEY("account","observed_at","kind")
);
--> statement-breakpoint
CREATE INDEX "risk_lending_events_pool_idx" ON "risk_lending_events" USING btree ("pool","block_time");--> statement-breakpoint
CREATE INDEX "risk_lending_events_kind_idx" ON "risk_lending_events" USING btree ("kind","block_time");--> statement-breakpoint
CREATE INDEX "risk_lending_snapshots_market_idx" ON "risk_lending_snapshots" USING btree ("market","observed_at");