// Reads mainnet (read-only) and writes everything a local validator needs to replay one
// USDC -> SPYx swap for a vault that only exists locally:
//   out/route.json          the Jupiter quote and swap instruction, frozen
//   out/funded-usdc.json    a made-up USDC token account for the vault or owner (local only)
//   out/start-validator.sh  solana-test-validator with every needed account cloned
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { getAssociatedTokenAddressSync, TOKEN_PROGRAM_ID } from '@solana/spl-token';
import { Connection, PublicKey } from '@solana/web3.js';
import {
  fetchRoute,
  loadKeypair,
  MAINNET_RPC,
  OUT,
  PROGRAM_ID,
  ROOT,
  SPYX,
  USDC,
  vaultAtas,
  vaultPda,
} from './common.ts';

const BPF_UPGRADEABLE = 'BPFLoaderUpgradeab1e11111111111111111111111';
const BUILTIN = new Set([
  '11111111111111111111111111111111',
  'ComputeBudget111111111111111111111111111111',
  'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
  'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  'Memo1UhkJRfHyvLMcVucJwxXeuD728EGPRxuBQNq2F',
  'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr',
]);

const owner = loadKeypair(process.env.OWNER_KEYPAIR ?? resolve(ROOT, 'keys/local-owner.json'));
const basketId = BigInt(process.env.BASKET_ID ?? '1');
const amount = BigInt(process.env.AMOUNT ?? '10000000'); // 10 USDC
const dexes = process.env.DEXES ?? 'Raydium CLMM'; // deterministic AMM: replays from a snapshot
const cloneToken2022 = process.env.CLONE_TOKEN_2022 === '1';

const vault = vaultPda(owner.publicKey, basketId);
const atas = vaultAtas(vault);
const mainnet = new Connection(MAINNET_RPC, 'confirmed');

const route = await fetchRoute(vault, {
  amount,
  dexes: dexes === 'any' ? undefined : dexes,
  onlyDirectRoutes: process.env.DIRECT !== '0',
  maxAccounts: process.env.MAX_ACCOUNTS ? Number(process.env.MAX_ACCOUNTS) : undefined,
  useSharedAccounts: process.env.SHARED === undefined ? undefined : process.env.SHARED === '1',
});

mkdirSync(OUT, { recursive: true });
writeFileSync(resolve(OUT, 'route.json'), JSON.stringify(route, null, 2));

// Every account the swap touches, plus the lookup tables themselves and both mints.
const local = new Set([
  vault.toBase58(),
  atas.usdc.toBase58(),
  atas.spyx.toBase58(),
  owner.publicKey.toBase58(),
]);
const wanted = new Set<string>([USDC.toBase58(), SPYX.toBase58(), route.swapInstruction.programId]);
for (const a of route.swapInstruction.accounts) wanted.add(a.pubkey);
for (const a of route.addressLookupTableAddresses) wanted.add(a);
if (cloneToken2022) BUILTIN.delete('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb');
const keys = [...wanted].filter((k) => !local.has(k) && !BUILTIN.has(k) && !k.startsWith('Sysvar'));

const infos = await mainnet.getMultipleAccountsInfo(keys.map((k) => new PublicKey(k)));
const clone: string[] = [];
const cloneProgram: string[] = [];
const missing: string[] = [];
keys.forEach((k, i) => {
  const info = infos[i];
  if (!info) missing.push(k);
  else if (info.executable && info.owner.toBase58() === BPF_UPGRADEABLE) cloneProgram.push(k);
  else clone.push(k);
});

// A made-up USDC token account written straight into genesis. Local only; no real USDC.
// FUND=vault (default) funds the vault directly; FUND=owner funds the owner's wallet so the
// mainnet flow (deposit, swap, withdraw) can be rehearsed end to end.
const fundOwner = process.env.FUND === 'owner';
const holder = fundOwner ? owner.publicKey : vault;
const funded = fundOwner ? getAssociatedTokenAddressSync(USDC, owner.publicKey) : atas.usdc;
const data = Buffer.alloc(165);
USDC.toBuffer().copy(data, 0);
holder.toBuffer().copy(data, 32);
data.writeBigUInt64LE(amount * 2n, 64);
data[108] = 1; // AccountState::Initialized
writeFileSync(
  resolve(OUT, 'funded-usdc.json'),
  JSON.stringify({
    pubkey: funded.toBase58(),
    account: {
      lamports: 2039280,
      data: [data.toString('base64'), 'base64'],
      owner: TOKEN_PROGRAM_ID.toBase58(),
      executable: false,
      rentEpoch: 0,
      space: 165,
    },
  }),
);

const slot = await mainnet.getSlot('confirmed');
const sh = [
  '#!/bin/sh',
  '# Generated by scripts/prepare-local.ts. Clones are read-only RPC calls to mainnet.',
  `cd "${ROOT}"`,
  'exec solana-test-validator --reset --quiet \\',
  '  --ledger test-ledger \\',
  `  --url ${MAINNET_RPC} \\`,
  `  --warp-slot ${slot} \\`,
  `  --bpf-program ${PROGRAM_ID.toBase58()} target/deploy/vault_swap.so \\`,
  `  --account ${funded.toBase58()} out/funded-usdc.json \\`,
  ...cloneProgram.map((k) => `  --clone-upgradeable-program ${k} \\`),
  ...clone.map((k) => `  --clone ${k} \\`),
  '  --rpc-port 8899',
  '',
].join('\n');
writeFileSync(resolve(OUT, 'start-validator.sh'), sh, { mode: 0o755 });

console.log(
  JSON.stringify(
    {
      owner: owner.publicKey.toBase58(),
      vault: vault.toBase58(),
      route: route.quote.routePlan.map((r: any) => r.swapInfo.label),
      inAmount: route.quote.inAmount,
      outAmount: route.quote.outAmount,
      minOut: route.quote.otherAmountThreshold,
      jupiterIxAccounts: route.swapInstruction.accounts.length,
      jupiterSetupInstructionsIgnored: route.setupInstructions.length,
      lookupTables: route.addressLookupTableAddresses,
      clonedAccounts: clone.length,
      clonedPrograms: cloneProgram,
      notOnMainnet: missing,
      warpSlot: slot,
    },
    null,
    2,
  ),
);
