// Generated by packages/sdk/scripts/gen-api-types.ts from packages/sdk/openapi.json. Do not edit:
// change the API's routes, run `pnpm openapi:emit`, then `pnpm --filter @colosseum/sdk api-types`.
// scripts/api-types.test.ts fails while this file is not what the committed document gives.

/** POST /v1/baskets/personalize: body. Make a plan from a goal and its limits, and store it. Nothing is bought */
export type PostBasketsPersonalizeBody = {
  sheet: {
    basketType: 'standard';
    goal: 'grow' | 'income' | 'protect';
    amountUsd: number;
    horizonMonths: number;
    risk: 'low' | 'medium' | 'high';
    themes: string[];
    country: string;
    chains: ('solana' | 'base' | 'robinhood')[];
    incomeTargetUsdMonthly?: number;
    rules: {
      useHoldings: boolean;
      glide: boolean;
    };
    language: 'pt' | 'en';
    currency?: string;
    obligations?: {
      month: string;
      amount: number;
      currency: string;
    }[];
    sleeves?: (
      | {
          kind: 'goal';
          shareBps: number;
        }
      | {
          kind: 'theme';
          shareBps: number;
          theme: string;
        }
      | {
          kind: 'safe_yield';
          shareBps: number;
        }
    )[];
    restoreSplit?: boolean;
    limits?: {
      mustKeepUsd?: number;
      mayNeedInMonths?: number;
      creditTolerance?: 'none' | 'limited' | 'accept';
      cannotHold?: {
        classes?: ('stock' | 'etf' | 'gold' | 'commodity' | 'dollar_yield' | 'crypto')[];
        underlyings?: string[];
        assets?: string[];
      };
    };
  };
};

/** POST /v1/baskets/personalize: response. Make a plan from a goal and its limits, and store it. Nothing is bought */
export type PostBasketsPersonalizeResponse = {
  id: string;
  proposal: {
    sheet: {
      basketType: 'standard';
      goal: 'grow' | 'income' | 'protect';
      amountUsd: number;
      horizonMonths: number;
      risk: 'low' | 'medium' | 'high';
      themes: string[];
      country: string;
      chains: ('solana' | 'base' | 'robinhood')[];
      incomeTargetUsdMonthly?: number;
      rules: {
        useHoldings: boolean;
        glide: boolean;
      };
      language: 'pt' | 'en';
      currency?: string;
      obligations?: {
        month: string;
        amount: number;
        currency: string;
      }[];
      sleeves?: (
        | {
            kind: 'goal';
            shareBps: number;
          }
        | {
            kind: 'theme';
            shareBps: number;
            theme: string;
          }
        | {
            kind: 'safe_yield';
            shareBps: number;
          }
      )[];
      restoreSplit?: boolean;
    };
    engineVersion: string;
    paramsHash: string;
    shelfVersion: string;
    inputsHash: string;
    lines: {
      chain: 'solana' | 'base' | 'robinhood';
      assetId: string;
      viaIndex?: string;
      weightBps: number;
      amountUsd: number;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    recipes: {
      chain: 'solana' | 'base' | 'robinhood';
      amountUsd: number;
      components: (
        | {
            kind: 'asset';
            asset: string;
            weightBps: number;
          }
        | {
            kind: 'index';
            family: string;
            weightBps: number;
          }
      )[];
    }[];
    removed: {
      ref: string;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    card: {
      moneyTodayUsd: number;
      termMonths: number;
      cashFlow: 'none' | 'monthly' | 'at_end';
      expectedReturn: {
        lowPct: number;
        highPct: number;
        basis: string;
        lossInFallUsd: number;
      };
      exit: {
        text: string;
        costBps: number | null;
      };
    };
    verdict?: {
      met: boolean;
      gapUsdMonthly: number;
      ways: {
        change: string;
        closesGap: boolean;
      }[];
    };
    flags: string[];
    observations: {
      source: string;
      method: string;
      fetchedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      id: string;
      kind: 'yield' | 'price' | 'liquidity' | 'fx';
    }[];
    disclaimer: string;
  };
  rollUp: {
    byIssuer: {
      key: string;
      bps: number;
    }[];
    byChain: {
      key: string;
      bps: number;
    }[];
    byClass: {
      key: string;
      bps: number;
    }[];
    flags: string[];
    exit: {
      quotedBps: number | null;
      quotedAt: string | null;
      measuredWorstBps: number | null;
      measuredShareBps: number;
    };
  };
};

/** POST /v1/baskets/propose: body. Make a plan from a goal and its limits for a person to open from a link. Nothing is bought */
export type PostBasketsProposeBody = {
  sheet: {
    basketType: 'standard';
    goal: 'grow' | 'income' | 'protect';
    amountUsd: number;
    horizonMonths: number;
    risk: 'low' | 'medium' | 'high';
    themes: string[];
    country: string;
    chains: ('solana' | 'base' | 'robinhood')[];
    incomeTargetUsdMonthly?: number;
    rules: {
      useHoldings: boolean;
      glide: boolean;
    };
    language: 'pt' | 'en';
    currency?: string;
    obligations?: {
      month: string;
      amount: number;
      currency: string;
    }[];
    sleeves?: (
      | {
          kind: 'goal';
          shareBps: number;
        }
      | {
          kind: 'theme';
          shareBps: number;
          theme: string;
        }
      | {
          kind: 'safe_yield';
          shareBps: number;
        }
    )[];
    restoreSplit?: boolean;
    limits?: {
      mustKeepUsd?: number;
      mayNeedInMonths?: number;
      creditTolerance?: 'none' | 'limited' | 'accept';
      cannotHold?: {
        classes?: ('stock' | 'etf' | 'gold' | 'commodity' | 'dollar_yield' | 'crypto')[];
        underlyings?: string[];
        assets?: string[];
      };
    };
  };
};

/** POST /v1/baskets/propose: response. Make a plan from a goal and its limits for a person to open from a link. Nothing is bought */
export type PostBasketsProposeResponse = {
  id: string;
  proposal: {
    sheet: {
      basketType: 'standard';
      goal: 'grow' | 'income' | 'protect';
      amountUsd: number;
      horizonMonths: number;
      risk: 'low' | 'medium' | 'high';
      themes: string[];
      country: string;
      chains: ('solana' | 'base' | 'robinhood')[];
      incomeTargetUsdMonthly?: number;
      rules: {
        useHoldings: boolean;
        glide: boolean;
      };
      language: 'pt' | 'en';
      currency?: string;
      obligations?: {
        month: string;
        amount: number;
        currency: string;
      }[];
      sleeves?: (
        | {
            kind: 'goal';
            shareBps: number;
          }
        | {
            kind: 'theme';
            shareBps: number;
            theme: string;
          }
        | {
            kind: 'safe_yield';
            shareBps: number;
          }
      )[];
      restoreSplit?: boolean;
    };
    engineVersion: string;
    paramsHash: string;
    shelfVersion: string;
    inputsHash: string;
    lines: {
      chain: 'solana' | 'base' | 'robinhood';
      assetId: string;
      viaIndex?: string;
      weightBps: number;
      amountUsd: number;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    recipes: {
      chain: 'solana' | 'base' | 'robinhood';
      amountUsd: number;
      components: (
        | {
            kind: 'asset';
            asset: string;
            weightBps: number;
          }
        | {
            kind: 'index';
            family: string;
            weightBps: number;
          }
      )[];
    }[];
    removed: {
      ref: string;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    card: {
      moneyTodayUsd: number;
      termMonths: number;
      cashFlow: 'none' | 'monthly' | 'at_end';
      expectedReturn: {
        lowPct: number;
        highPct: number;
        basis: string;
        lossInFallUsd: number;
      };
      exit: {
        text: string;
        costBps: number | null;
      };
    };
    verdict?: {
      met: boolean;
      gapUsdMonthly: number;
      ways: {
        change: string;
        closesGap: boolean;
      }[];
    };
    flags: string[];
    observations: {
      source: string;
      method: string;
      fetchedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      id: string;
      kind: 'yield' | 'price' | 'liquidity' | 'fx';
    }[];
    disclaimer: string;
  };
  rollUp: {
    byIssuer: {
      key: string;
      bps: number;
    }[];
    byChain: {
      key: string;
      bps: number;
    }[];
    byClass: {
      key: string;
      bps: number;
    }[];
    flags: string[];
    exit: {
      quotedBps: number | null;
      quotedAt: string | null;
      measuredWorstBps: number | null;
      measuredShareBps: number;
    };
  };
};

/** GET /v1/baskets/{id}: params. A stored plan by its id: one made from a link, or the caller’s own */
export type GetBasketsByIdParams = {
  id: string;
};

/** GET /v1/baskets/{id}: response. A stored plan by its id: one made from a link, or the caller’s own */
export type GetBasketsByIdResponse = {
  id: string;
  proposal: {
    sheet: {
      basketType: 'standard';
      goal: 'grow' | 'income' | 'protect';
      amountUsd: number;
      horizonMonths: number;
      risk: 'low' | 'medium' | 'high';
      themes: string[];
      country: string;
      chains: ('solana' | 'base' | 'robinhood')[];
      incomeTargetUsdMonthly?: number;
      rules: {
        useHoldings: boolean;
        glide: boolean;
      };
      language: 'pt' | 'en';
      currency?: string;
      obligations?: {
        month: string;
        amount: number;
        currency: string;
      }[];
      sleeves?: (
        | {
            kind: 'goal';
            shareBps: number;
          }
        | {
            kind: 'theme';
            shareBps: number;
            theme: string;
          }
        | {
            kind: 'safe_yield';
            shareBps: number;
          }
      )[];
      restoreSplit?: boolean;
    };
    engineVersion: string;
    paramsHash: string;
    shelfVersion: string;
    inputsHash: string;
    lines: {
      chain: 'solana' | 'base' | 'robinhood';
      assetId: string;
      viaIndex?: string;
      weightBps: number;
      amountUsd: number;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    recipes: {
      chain: 'solana' | 'base' | 'robinhood';
      amountUsd: number;
      components: (
        | {
            kind: 'asset';
            asset: string;
            weightBps: number;
          }
        | {
            kind: 'index';
            family: string;
            weightBps: number;
          }
      )[];
    }[];
    removed: {
      ref: string;
      reasons: {
        rule: string;
        inputs: string[];
        params: {
          [key: string]: string | number;
        };
        text: string;
      }[];
    }[];
    card: {
      moneyTodayUsd: number;
      termMonths: number;
      cashFlow: 'none' | 'monthly' | 'at_end';
      expectedReturn: {
        lowPct: number;
        highPct: number;
        basis: string;
        lossInFallUsd: number;
      };
      exit: {
        text: string;
        costBps: number | null;
      };
    };
    verdict?: {
      met: boolean;
      gapUsdMonthly: number;
      ways: {
        change: string;
        closesGap: boolean;
      }[];
    };
    flags: string[];
    observations: {
      source: string;
      method: string;
      fetchedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      id: string;
      kind: 'yield' | 'price' | 'liquidity' | 'fx';
    }[];
    disclaimer: string;
  };
  fromLink: boolean;
};

/** GET /v1/config: response. Feature flags and the chains this deployment runs on */
export type GetConfigResponse = {
  flags: {
    chainMode: Record<'solana' | 'base' | 'robinhood', 'live' | 'readonly' | 'mock' | 'off'>;
    autoFollow: Record<'solana' | 'base' | 'robinhood', boolean>;
    keeperEnabled: boolean;
    agentSurface: boolean;
    legacyStructurer: boolean;
  };
  chains: {
    id: 'solana' | 'base' | 'robinhood';
    family: 'solana' | 'evm';
    name: string;
    network: 'mainnet' | 'testnet' | 'local';
    networkName: string;
    evmChainId: number | null;
    explorerTx: string | null;
    router: (string | string) | null;
    priceSource: {
      kind: 'scope' | 'chainlink' | 'none';
      address: (string | string) | null;
    };
    contracts: {
      [key: string]: string | string;
    };
    mode: 'live' | 'readonly' | 'mock' | 'off';
    provenance: ('live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset') | null;
  }[];
};

/** GET /v1/funding: query. What the signed-in wallet is missing on its chain: the dollar token and native gas */
export type GetFundingQuery = {
  wallet?: string | string;
  amountUsd?: number;
  proposalId?: string;
  family?: string;
  vault?: string | string;
  vaultChain?: 'solana' | 'base' | 'robinhood';
};

/** GET /v1/funding: response. What the signed-in wallet is missing on its chain: the dollar token and native gas */
export type GetFundingResponse = {
  chain: 'solana' | 'base' | 'robinhood';
  name: string;
  mode: 'live' | 'readonly' | 'mock' | 'off';
  provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  wallet: string | string;
  cash: {
    source: string;
    method: string;
    fetchedAt: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    symbol: string;
    decimals: number;
    haveRaw: string;
    needRaw: string;
    missingRaw: string;
    asset: string;
  };
  gas: {
    source: string;
    method: string;
    fetchedAt: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    symbol: string;
    decimals: number;
    haveRaw: string;
    needRaw: string;
    missingRaw: string;
  };
  steps: number;
  newVault: boolean;
  ok: boolean;
  testFunds?: boolean;
};

/** GET /v1/indexes/{slug}: params. A shared portfolio, its recipes read from their chains */
export type GetIndexesBySlugParams = {
  slug: string;
};

/** GET /v1/indexes/{slug}: query. A shared portfolio, its recipes read from their chains */
export type GetIndexesBySlugQuery = {
  chain?: 'solana' | 'base' | 'robinhood';
};

/** GET /v1/indexes/{slug}: response. A shared portfolio, its recipes read from their chains */
export type GetIndexesBySlugResponse = {
  family: {
    familyId: string;
    slug: string;
    name: string;
    copy: string;
    kind: 'index' | 'single';
    platform: boolean;
    creatorKind: 'platform' | 'community';
    chains: ('solana' | 'base' | 'robinhood')[];
    recipes: {
      chain: 'solana' | 'base' | 'robinhood';
      name: string;
      onchainId: string;
      creator: string | string;
      active: {
        version: number;
        effectiveAt: number;
        components: {
          asset: string;
          weightBps: number;
        }[];
        metaHash: string;
        status: 'active' | 'pending' | 'superseded' | 'cancelled';
      };
      pending: {
        version: number;
        effectiveAt: number;
        components: {
          asset: string;
          weightBps: number;
        }[];
        metaHash: string;
        status: 'active' | 'pending' | 'superseded' | 'cancelled';
      } | null;
      autoFollow:
        | {
            offered: true;
          }
        | {
            offered: false;
            reason: 'no_oracle' | 'switched_off';
            assets: string[];
          };
      textMatches: ('active' | 'pending') | null;
      source: 'chain' | 'cache';
      observedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    }[];
  };
  disclaimer: string;
};

/** GET /v1/indexes/{slug}/versions: params. Every version of a shared portfolio the server has seen, per chain, newest first */
export type GetIndexesBySlugVersionsParams = {
  slug: string;
};

/** GET /v1/indexes/{slug}/versions: query. Every version of a shared portfolio the server has seen, per chain, newest first */
export type GetIndexesBySlugVersionsQuery = {
  chain?: 'solana' | 'base' | 'robinhood';
};

/** GET /v1/indexes/{slug}/versions: response. Every version of a shared portfolio the server has seen, per chain, newest first */
export type GetIndexesBySlugVersionsResponse = {
  familyId: string;
  slug: string;
  chains: {
    chain: 'solana' | 'base' | 'robinhood';
    onchainId: string;
    source: 'chain' | 'cache';
    observedAt: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    versions: {
      version: number;
      effectiveAt: number;
      components: {
        asset: string;
        weightBps: number;
      }[];
      metaHash: string;
      status: 'active' | 'pending' | 'superseded' | 'cancelled';
    }[];
  }[];
};

/** GET /v1/me: response. The signed-in person: their wallets, and the chain their new plans are made on */
export type GetMeResponse = {
  userId: string;
  wallets: {
    family: 'solana' | 'evm';
    address: string | string;
    kind: 'embedded' | 'external';
  }[];
  chain: ('solana' | 'base' | 'robinhood') | null;
  chainSource: ('picked' | 'wallet') | null;
  chainOptions: ('solana' | 'base' | 'robinhood')[];
};

/** PUT /v1/me/chain: body. Pick or switch the chain your new plans are made on */
export type PutMeChainBody = {
  chain: 'solana' | 'base' | 'robinhood';
};

/** PUT /v1/me/chain: response. Pick or switch the chain your new plans are made on */
export type PutMeChainResponse = {
  userId: string;
  wallets: {
    family: 'solana' | 'evm';
    address: string | string;
    kind: 'embedded' | 'external';
  }[];
  chain: ('solana' | 'base' | 'robinhood') | null;
  chainSource: ('picked' | 'wallet') | null;
  chainOptions: ('solana' | 'base' | 'robinhood')[];
};

/** GET /v1/me/plans: query. The signed-in person’s plans, with the goal each was built for and its buys */
export type GetMePlansQuery = {
  limit?: number;
  before?: string;
};

/** GET /v1/me/plans: response. The signed-in person’s plans, with the goal each was built for and its buys */
export type GetMePlansResponse = {
  plans: {
    id: string;
    createdAt: string;
    fromLink: boolean;
    chain: 'solana' | 'base' | 'robinhood';
    sheet: {
      basketType: 'standard';
      goal: 'grow' | 'income' | 'protect';
      amountUsd: number;
      horizonMonths: number;
      risk: 'low' | 'medium' | 'high';
      themes: string[];
      country: string;
      chains: ('solana' | 'base' | 'robinhood')[];
      incomeTargetUsdMonthly?: number;
      rules: {
        useHoldings: boolean;
        glide: boolean;
      };
      language: 'pt' | 'en';
      currency?: string;
      obligations?: {
        month: string;
        amount: number;
        currency: string;
      }[];
      sleeves?: (
        | {
            kind: 'goal';
            shareBps: number;
          }
        | {
            kind: 'theme';
            shareBps: number;
            theme: string;
          }
        | {
            kind: 'safe_yield';
            shareBps: number;
          }
      )[];
      restoreSplit?: boolean;
    };
    card: {
      moneyTodayUsd: number;
      termMonths: number;
      cashFlow: 'none' | 'monthly' | 'at_end';
      expectedReturn: {
        lowPct: number;
        highPct: number;
        basis: string;
        lossInFallUsd: number;
      };
      exit: {
        text: string;
        costBps: number | null;
      };
    };
    verdict: {
      met: boolean;
      gapUsdMonthly: number;
      ways: {
        change: string;
        closesGap: boolean;
      }[];
    } | null;
    bought: boolean;
    orders: {
      id: string;
      createdAt: string;
      amountUsd: number;
      status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
      deposited: boolean;
    }[];
    vault: {
      chain: 'solana' | 'base' | 'robinhood';
      basketId: string;
    } | null;
  }[];
  next: string | null;
};

/** POST /v1/orders: body. Plan an order from an intent. Nothing is built or signed */
export type PostOrdersBody =
  | {
      type: 'buy';
      owner: {
        solana?: string;
        evm?: string;
      };
      amountUsd: number;
      maxSlippageBps?: number;
      proposalId?: string;
      family?: string;
      version?: number;
      vault?: {
        chain: 'solana' | 'base' | 'robinhood';
        address: string | string;
      };
      chains?: unknown;
    }
  | {
      type: 'rebalance';
      vaults: (string | string)[];
      reason: 'manual' | 'index_update' | 'drift';
    }
  | {
      type: 'follow';
      vault: string | string;
      family: string;
      autoFollow: boolean;
      version?: number;
    }
  | {
      type: 'publish';
      creator: {
        solana?: string;
        evm?: string;
      };
      family: string;
      familyId?: string;
      name: string;
      copy: string;
      recipes: {
        chain: 'solana' | 'base' | 'robinhood';
        components: (
          | {
              kind: 'asset';
              asset: string;
              weightBps: number;
            }
          | {
              kind: 'index';
              family: string;
              weightBps: number;
            }
        )[];
      }[];
    }
  | {
      type: 'withdraw';
      vaults: (string | string)[];
      sellToCash: boolean;
    }
  | {
      type: 'settings';
      vault: string | string;
      autoFollow: boolean;
    };

/** POST /v1/orders: response. Plan an order from an intent. Nothing is built or signed */
export type PostOrdersResponse = {
  id: string;
  type: 'buy' | 'rebalance' | 'follow' | 'publish' | 'withdraw' | 'settings';
  owner: {
    solana?: string;
    evm?: string;
  };
  summary: string;
  depositRaw?: string;
  basketId?: string;
  continues?: string;
  legs: {
    id: string;
    orderId: string | null;
    chain: 'solana' | 'base' | 'robinhood';
    seq: number;
    kind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    signer: 'owner' | 'keeper';
    description: string;
    cashRaw?: string;
    trades: {
      sell: string;
      buy: string;
      amountInRaw: string;
    }[];
    expected: {
      inRaw: string;
      outRaw: string;
      minOutRaw: string;
      costBps: number;
    }[];
    status: 'planned' | 'built' | 'sent' | 'confirmed' | 'failed' | 'expired' | 'skipped';
    attempt: number;
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    error: {
      code: string;
      message: string;
      retryable: boolean;
    } | null;
    trigger: 'manual' | 'index_update' | 'drift' | 'liquidity_breach';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  }[];
  warnings: {
    code: string;
    text: string;
  }[];
  needsConsent: ('auto_follow_on' | 'new_asset' | 'publish')[];
  fees: {
    kind: string;
    bps: number;
  }[];
  preparedBy: 'app' | 'api' | 'mcp';
  agentLabel?: string;
  status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
  approvalUrl: string;
  expiresAt: number;
  createdAt: string;
  disclaimer: string;
  attempts: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  }[];
};

/** GET /v1/orders/{id}: params. An order with its legs and every attempt at them */
export type GetOrdersByIdParams = {
  id: string;
};

/** GET /v1/orders/{id}: response. An order with its legs and every attempt at them */
export type GetOrdersByIdResponse = {
  id: string;
  type: 'buy' | 'rebalance' | 'follow' | 'publish' | 'withdraw' | 'settings';
  owner: {
    solana?: string;
    evm?: string;
  };
  summary: string;
  depositRaw?: string;
  basketId?: string;
  continues?: string;
  legs: {
    id: string;
    orderId: string | null;
    chain: 'solana' | 'base' | 'robinhood';
    seq: number;
    kind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    signer: 'owner' | 'keeper';
    description: string;
    cashRaw?: string;
    trades: {
      sell: string;
      buy: string;
      amountInRaw: string;
    }[];
    expected: {
      inRaw: string;
      outRaw: string;
      minOutRaw: string;
      costBps: number;
    }[];
    status: 'planned' | 'built' | 'sent' | 'confirmed' | 'failed' | 'expired' | 'skipped';
    attempt: number;
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    error: {
      code: string;
      message: string;
      retryable: boolean;
    } | null;
    trigger: 'manual' | 'index_update' | 'drift' | 'liquidity_breach';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  }[];
  warnings: {
    code: string;
    text: string;
  }[];
  needsConsent: ('auto_follow_on' | 'new_asset' | 'publish')[];
  fees: {
    kind: string;
    bps: number;
  }[];
  preparedBy: 'app' | 'api' | 'mcp';
  agentLabel?: string;
  status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
  approvalUrl: string;
  expiresAt: number;
  createdAt: string;
  disclaimer: string;
  attempts: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  }[];
};

/** POST /v1/orders/{id}/continue: params. Finish a buy with the cash already in its vault. Nothing is deposited */
export type PostOrdersByIdContinueParams = {
  id: string;
};

/** POST /v1/orders/{id}/continue: response. Finish a buy with the cash already in its vault. Nothing is deposited */
export type PostOrdersByIdContinueResponse = {
  id: string;
  type: 'buy' | 'rebalance' | 'follow' | 'publish' | 'withdraw' | 'settings';
  owner: {
    solana?: string;
    evm?: string;
  };
  summary: string;
  depositRaw?: string;
  basketId?: string;
  continues?: string;
  legs: {
    id: string;
    orderId: string | null;
    chain: 'solana' | 'base' | 'robinhood';
    seq: number;
    kind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    signer: 'owner' | 'keeper';
    description: string;
    cashRaw?: string;
    trades: {
      sell: string;
      buy: string;
      amountInRaw: string;
    }[];
    expected: {
      inRaw: string;
      outRaw: string;
      minOutRaw: string;
      costBps: number;
    }[];
    status: 'planned' | 'built' | 'sent' | 'confirmed' | 'failed' | 'expired' | 'skipped';
    attempt: number;
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    error: {
      code: string;
      message: string;
      retryable: boolean;
    } | null;
    trigger: 'manual' | 'index_update' | 'drift' | 'liquidity_breach';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  }[];
  warnings: {
    code: string;
    text: string;
  }[];
  needsConsent: ('auto_follow_on' | 'new_asset' | 'publish')[];
  fees: {
    kind: string;
    bps: number;
  }[];
  preparedBy: 'app' | 'api' | 'mcp';
  agentLabel?: string;
  status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
  approvalUrl: string;
  expiresAt: number;
  createdAt: string;
  disclaimer: string;
  attempts: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  }[];
};

/** POST /v1/orders/{id}/legs/{legId}/build: params. Build one leg: a fresh unsigned transaction and the attempt that records it */
export type PostOrdersByIdLegsByLegIdBuildParams = {
  id: string;
  legId: string;
};

/** POST /v1/orders/{id}/legs/{legId}/build: response. Build one leg: a fresh unsigned transaction and the attempt that records it */
export type PostOrdersByIdLegsByLegIdBuildResponse = {
  tx: {
    chain: 'solana' | 'evm';
    payload: string;
    evm?: {
      to: string;
      value: string;
      chainId: number;
      nonce?: number;
      gas?: number;
    };
    description: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    lastValidBlockHeight?: number;
    legKind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    chainId: 'solana' | 'base' | 'robinhood';
    signer: string | string;
    feePayer?: string | string;
    messageHash: string;
    preview: {
      source: string;
      method: string;
      fetchedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      summary: string;
      simulated: boolean;
      feeNativeRaw: string;
      changes: {
        holder: 'wallet' | 'vault';
        asset: string;
        deltaRaw: string;
      }[];
      minimums: {
        sell: string;
        buy: string;
        inRaw: string;
        minOutRaw: string;
      }[];
    };
    legId: string;
    attemptId: string;
  };
  attempt: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  };
};

/** POST /v1/orders/{id}/legs/{legId}/cancel: params. Cancel the latest attempt at a leg, so the leg can be built again */
export type PostOrdersByIdLegsByLegIdCancelParams = {
  id: string;
  legId: string;
};

/** POST /v1/orders/{id}/legs/{legId}/cancel: response. Cancel the latest attempt at a leg, so the leg can be built again */
export type PostOrdersByIdLegsByLegIdCancelResponse = {
  id: string;
  type: 'buy' | 'rebalance' | 'follow' | 'publish' | 'withdraw' | 'settings';
  owner: {
    solana?: string;
    evm?: string;
  };
  summary: string;
  depositRaw?: string;
  basketId?: string;
  continues?: string;
  legs: {
    id: string;
    orderId: string | null;
    chain: 'solana' | 'base' | 'robinhood';
    seq: number;
    kind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    signer: 'owner' | 'keeper';
    description: string;
    cashRaw?: string;
    trades: {
      sell: string;
      buy: string;
      amountInRaw: string;
    }[];
    expected: {
      inRaw: string;
      outRaw: string;
      minOutRaw: string;
      costBps: number;
    }[];
    status: 'planned' | 'built' | 'sent' | 'confirmed' | 'failed' | 'expired' | 'skipped';
    attempt: number;
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    error: {
      code: string;
      message: string;
      retryable: boolean;
    } | null;
    trigger: 'manual' | 'index_update' | 'drift' | 'liquidity_breach';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  }[];
  warnings: {
    code: string;
    text: string;
  }[];
  needsConsent: ('auto_follow_on' | 'new_asset' | 'publish')[];
  fees: {
    kind: string;
    bps: number;
  }[];
  preparedBy: 'app' | 'api' | 'mcp';
  agentLabel?: string;
  status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
  approvalUrl: string;
  expiresAt: number;
  createdAt: string;
  disclaimer: string;
  attempts: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  }[];
};

/** POST /v1/orders/{id}/legs/{legId}/report: params. Report a leg as sent, by its transaction id or by signed bytes to relay */
export type PostOrdersByIdLegsByLegIdReportParams = {
  id: string;
  legId: string;
};

/** POST /v1/orders/{id}/legs/{legId}/report: body. Report a leg as sent, by its transaction id or by signed bytes to relay */
export type PostOrdersByIdLegsByLegIdReportBody =
  | {
      txId: string;
    }
  | {
      signedTx: string;
    };

/** POST /v1/orders/{id}/legs/{legId}/report: response. Report a leg as sent, by its transaction id or by signed bytes to relay */
export type PostOrdersByIdLegsByLegIdReportResponse = {
  id: string;
  type: 'buy' | 'rebalance' | 'follow' | 'publish' | 'withdraw' | 'settings';
  owner: {
    solana?: string;
    evm?: string;
  };
  summary: string;
  depositRaw?: string;
  basketId?: string;
  continues?: string;
  legs: {
    id: string;
    orderId: string | null;
    chain: 'solana' | 'base' | 'robinhood';
    seq: number;
    kind:
      | 'approve'
      | 'create_vault'
      | 'deposit'
      | 'swap'
      | 'set_targets'
      | 'accept_version'
      | 'set_auto_follow'
      | 'withdraw'
      | 'publish'
      | 'adopt_version'
      | 'keeper_leg';
    signer: 'owner' | 'keeper';
    description: string;
    cashRaw?: string;
    trades: {
      sell: string;
      buy: string;
      amountInRaw: string;
    }[];
    expected: {
      inRaw: string;
      outRaw: string;
      minOutRaw: string;
      costBps: number;
    }[];
    status: 'planned' | 'built' | 'sent' | 'confirmed' | 'failed' | 'expired' | 'skipped';
    attempt: number;
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    error: {
      code: string;
      message: string;
      retryable: boolean;
    } | null;
    trigger: 'manual' | 'index_update' | 'drift' | 'liquidity_breach';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  }[];
  warnings: {
    code: string;
    text: string;
  }[];
  needsConsent: ('auto_follow_on' | 'new_asset' | 'publish')[];
  fees: {
    kind: string;
    bps: number;
  }[];
  preparedBy: 'app' | 'api' | 'mcp';
  agentLabel?: string;
  status: 'open' | 'partial' | 'done' | 'failed' | 'expired';
  approvalUrl: string;
  expiresAt: number;
  createdAt: string;
  disclaimer: string;
  attempts: {
    id: string;
    legId: string;
    n: number;
    messageHash: string;
    nonce: number | null;
    status: 'built' | 'sent' | 'confirmed' | 'failed' | 'expired';
    txId: string | null;
    explorerUrl: string | null;
    validUntil: string | null;
    builtAt: string;
  }[];
};

/** GET /v1/portfolio: response. The signed-in person's vaults on every chain, with holdings, prices and drift */
export type GetPortfolioResponse = {
  chains: {
    chain: 'solana' | 'base' | 'robinhood';
    name: string;
    mode: 'live' | 'readonly' | 'mock' | 'off';
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    vaults: {
      chain: 'solana' | 'base' | 'robinhood';
      address: string | string;
      owner: string | string;
      basketId: string;
      recipeOnchainId: string | null;
      acceptedVersion: number;
      autoFollow: boolean;
      keeper: string | string;
      cash: {
        asset: string;
        raw: string;
        multiplier: string;
        display: string;
        scheduled?: {
          multiplier: string;
          effectiveAt: number;
        };
      };
      positions: {
        asset: string;
        raw: string;
        multiplier: string;
        display: string;
        scheduled?: {
          multiplier: string;
          effectiveAt: number;
        };
        targetBps: number;
        lastKeeperAt: number | null;
        valueUsd: string | null;
        weightBps: number;
        driftBps: number;
      }[];
      lossUsedBps: number;
      observedAt: string;
      pending: {
        version: number;
        effectiveAt: number;
        newAssets: string[];
      } | null;
      valueUsd: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      name?: string | null;
      planId?: string | null;
    }[];
    prices: {
      source: string;
      method: string;
      fetchedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
      asset: string;
      usdPerToken: string;
      ageSeconds: number;
      maxAgeSeconds: number;
      market: 'open' | 'closed' | 'unknown';
    }[];
  }[];
  unavailable: {
    chain: 'solana' | 'base' | 'robinhood';
    name: string;
    code: string;
    error: string;
    retryable: boolean;
  }[];
  disclaimer: string;
};

/** GET /v1/shelf: query. Every shared portfolio, or those with a recipe on one chain */
export type GetShelfQuery = {
  chain?: 'solana' | 'base' | 'robinhood';
};

/** GET /v1/shelf: response. Every shared portfolio, or those with a recipe on one chain */
export type GetShelfResponse = {
  families: {
    familyId: string;
    slug: string;
    name: string;
    copy: string;
    kind: 'index' | 'single';
    platform: boolean;
    creatorKind: 'platform' | 'community';
    chains: ('solana' | 'base' | 'robinhood')[];
    recipes: {
      chain: 'solana' | 'base' | 'robinhood';
      name: string;
      onchainId: string;
      creator: string | string;
      active: {
        version: number;
        effectiveAt: number;
        components: {
          asset: string;
          weightBps: number;
        }[];
        metaHash: string;
        status: 'active' | 'pending' | 'superseded' | 'cancelled';
      };
      pending: {
        version: number;
        effectiveAt: number;
        components: {
          asset: string;
          weightBps: number;
        }[];
        metaHash: string;
        status: 'active' | 'pending' | 'superseded' | 'cancelled';
      } | null;
      autoFollow:
        | {
            offered: true;
          }
        | {
            offered: false;
            reason: 'no_oracle' | 'switched_off';
            assets: string[];
          };
      textMatches: ('active' | 'pending') | null;
      source: 'chain' | 'cache';
      observedAt: string;
      provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    }[];
  }[];
  disclaimer: string;
};

/** POST /v1/testnet/fund: body. Test network only: send the signed-in wallet the test tokens and gas a buy is missing */
export type PostTestnetFundBody = {
  wallet?: string | string;
  amountUsd: number;
  proposalId?: string;
  family?: string;
  vault?: string | string;
  vaultChain?: 'solana' | 'base' | 'robinhood';
};

/** POST /v1/testnet/fund: response. Test network only: send the signed-in wallet the test tokens and gas a buy is missing */
export type PostTestnetFundResponse = {
  chain: 'solana' | 'base' | 'robinhood';
  provenance: 'sandbox';
  wallet: string | string;
  cash: {
    symbol: string;
    decimals: number;
    raw: string;
  };
  gas: {
    symbol: string;
    decimals: number;
    raw: string;
  };
  txIds: string[];
  left: number;
};

/** GET /v1/vaults/{chain}/{address}: params. One vault, read from its chain, for anybody */
export type GetVaultsByChainByAddressParams = {
  chain: 'solana' | 'base' | 'robinhood';
  address: string;
};

/** GET /v1/vaults/{chain}/{address}: response. One vault, read from its chain, for anybody */
export type GetVaultsByChainByAddressResponse = {
  chain: 'solana' | 'base' | 'robinhood';
  name: string;
  mode: 'live' | 'readonly' | 'mock' | 'off';
  provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  vault: {
    chain: 'solana' | 'base' | 'robinhood';
    address: string | string;
    owner: string | string;
    basketId: string;
    recipeOnchainId: string | null;
    acceptedVersion: number;
    autoFollow: boolean;
    keeper: string | string;
    cash: {
      asset: string;
      raw: string;
      multiplier: string;
      display: string;
      scheduled?: {
        multiplier: string;
        effectiveAt: number;
      };
    };
    positions: {
      asset: string;
      raw: string;
      multiplier: string;
      display: string;
      scheduled?: {
        multiplier: string;
        effectiveAt: number;
      };
      targetBps: number;
      lastKeeperAt: number | null;
      valueUsd: string | null;
      weightBps: number;
      driftBps: number;
    }[];
    lossUsedBps: number;
    observedAt: string;
    pending: {
      version: number;
      effectiveAt: number;
      newAssets: string[];
    } | null;
    valueUsd: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
  };
  prices: {
    source: string;
    method: string;
    fetchedAt: string;
    provenance: 'live' | 'mock' | 'sandbox' | 'fixture' | 'prior_dataset';
    asset: string;
    usdPerToken: string;
    ageSeconds: number;
    maxAgeSeconds: number;
    market: 'open' | 'closed' | 'unknown';
  }[];
  disclaimer: string;
};

/** PUT /v1/vaults/{chain}/{address}/name: params. Name a vault of yours, or clear its name */
export type PutVaultsByChainByAddressNameParams = {
  chain: 'solana' | 'base' | 'robinhood';
  address: string;
};

/** PUT /v1/vaults/{chain}/{address}/name: body. Name a vault of yours, or clear its name */
export type PutVaultsByChainByAddressNameBody = {
  name: string | null;
};

/** PUT /v1/vaults/{chain}/{address}/name: response. Name a vault of yours, or clear its name */
export type PutVaultsByChainByAddressNameResponse = {
  chain: 'solana' | 'base' | 'robinhood';
  address: string;
  name: string | null;
};

/** Every route of the document, by its method and path: what each takes and answers. */
export interface ApiRoutes {
  'POST /v1/baskets/personalize': {
    body: PostBasketsPersonalizeBody;
    response: PostBasketsPersonalizeResponse;
  };
  'POST /v1/baskets/propose': {
    body: PostBasketsProposeBody;
    response: PostBasketsProposeResponse;
  };
  'GET /v1/baskets/{id}': { params: GetBasketsByIdParams; response: GetBasketsByIdResponse };
  'GET /v1/config': { response: GetConfigResponse };
  'GET /v1/funding': { query: GetFundingQuery; response: GetFundingResponse };
  'GET /v1/indexes/{slug}': {
    params: GetIndexesBySlugParams;
    query: GetIndexesBySlugQuery;
    response: GetIndexesBySlugResponse;
  };
  'GET /v1/indexes/{slug}/versions': {
    params: GetIndexesBySlugVersionsParams;
    query: GetIndexesBySlugVersionsQuery;
    response: GetIndexesBySlugVersionsResponse;
  };
  'GET /v1/me': { response: GetMeResponse };
  'PUT /v1/me/chain': { body: PutMeChainBody; response: PutMeChainResponse };
  'GET /v1/me/plans': { query: GetMePlansQuery; response: GetMePlansResponse };
  'POST /v1/orders': { body: PostOrdersBody; response: PostOrdersResponse };
  'GET /v1/orders/{id}': { params: GetOrdersByIdParams; response: GetOrdersByIdResponse };
  'POST /v1/orders/{id}/continue': {
    params: PostOrdersByIdContinueParams;
    response: PostOrdersByIdContinueResponse;
  };
  'POST /v1/orders/{id}/legs/{legId}/build': {
    params: PostOrdersByIdLegsByLegIdBuildParams;
    response: PostOrdersByIdLegsByLegIdBuildResponse;
  };
  'POST /v1/orders/{id}/legs/{legId}/cancel': {
    params: PostOrdersByIdLegsByLegIdCancelParams;
    response: PostOrdersByIdLegsByLegIdCancelResponse;
  };
  'POST /v1/orders/{id}/legs/{legId}/report': {
    params: PostOrdersByIdLegsByLegIdReportParams;
    body: PostOrdersByIdLegsByLegIdReportBody;
    response: PostOrdersByIdLegsByLegIdReportResponse;
  };
  'GET /v1/portfolio': { response: GetPortfolioResponse };
  'GET /v1/shelf': { query: GetShelfQuery; response: GetShelfResponse };
  'POST /v1/testnet/fund': { body: PostTestnetFundBody; response: PostTestnetFundResponse };
  'GET /v1/vaults/{chain}/{address}': {
    params: GetVaultsByChainByAddressParams;
    response: GetVaultsByChainByAddressResponse;
  };
  'PUT /v1/vaults/{chain}/{address}/name': {
    params: PutVaultsByChainByAddressNameParams;
    body: PutVaultsByChainByAddressNameBody;
    response: PutVaultsByChainByAddressNameResponse;
  };
}
